## DO NOT EDIT THIS FILE UNLESS CODE BREAKS! ##

semester = "fall"    #Options are   "fall" and "spring"   
                    #Eventually, will add "summer1" and "summer2"
                    #SET THIS EVERY SEMESTER.  Will push semester to all lab files.

import numpy as np  #This package will let us use arrays to handle our data.  Arrays are very similar lists.
import matplotlib.pyplot as plt  #This package will let us plot our data easily.
from IPython.display import Image  #These two packages allow us to view images in the JupyterLab file.
from IPython.core.display import HTML
from mpl_toolkits.mplot3d import Axes3D
from statistics import mean

#allows for interactive plots and widgets in notebooks:
#%matplotlib inline      # Not sure what this used to do, but works fine without it.  Possibly from outdated version of matplotlib
import ipywidgets
from ipywidgets import *
import nbconvert
from IPython.display import display
from IPython.display import YouTubeVideo

from scipy.integrate import odeint

import datetime
from datetime import *
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, inch, portrait
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet


#Creates Excel back-up file
import openpyxl
from openpyxl import load_workbook
#import pandas as pd

def excelbackup(timestamp,labname):
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    workbook.save(labname+timestamp+".xlsx")

txl = datetime.today().strftime('%Y.%m.%d.%H.%M.%S')

#Creates the Section selection dropdown menu:
section = ipywidgets.Dropdown(
        options=["Select your section"],
        value="Select your section",
        description="Section:",
        disabled=False,
    )

#Creates the group number textbox:
group = ipywidgets.Text(
        value=None,
        placeholder="Type group number here",
        description="Group:",
        disabled=False,
    )

#Creates the group member names textbox for labs:
names = ipywidgets.Text(
        value=None,
        placeholder="Type group member names here",
        description="Names:",
        disabled=False,
    )

#Creates the group member names textbox for lab url:
url = ipywidgets.Text(
        value=None,
        placeholder="Copy-paste web address (URL) here",
        description="URL:",
        disabled=False,
    )

#Creates the name textbox for pre-labs:
#pl_names = ipywidgets.Text(
#        value=None,
#        placeholder="Type your name here",
#        description="Name:",
#        disabled=False,
#    )

#Initialized lab files.  Course number determines options for section number and time.
def course(inpt):
    if inpt == "1501fall":
        section.options = [
        "Select your section",
        "001 - MoWeTh 8am-9:55am",
        "002 - MoWeTh 10:10am-12:05pm",
        "003 - MoWeTh 12:20pm-2:15pm",
        "004 - MoWeTh 2:30pm-4:25pm",
        "005 - MoWeTh 4:40pm-6:35pm",
        "006 - TuThFr 8am-9:55am",
        "007 - TuThFr 10:10am-12:05pm",
        "008 - TuThFr 12:20pm-2:15pm"
        ]
    elif inpt == "1501spring":
        section.options = [
        "Select your section",
        "001 - MoWeTh 10:10am-12:05pm",
        "002 - MoWeTh 12:20pm-2:15pm",
        "003 - MoWeTh 2:30pm-4:25pm",
        "004 - MoWeTh 4:40pm-6:35pm",
        "005 - TuThFr 8am-9:55am",
        "006 - TuThFr 10:10am-12:05pm",
        "007 - TuThFr 12:20pm-2:15pm"
        ]
    elif inpt == "1502fall":
        section.options = [
        "Select your section",
        "001 - MoWeTh 10:10am-12:05pm",
        "002 - MoWeTh 12:20pm-2:15pm",
        "003 - MoWeTh 2:30pm-4:25pm",
        "004 - MoWeTh 4:40pm-6:35pm",
        "005 - TuThFr 8am-9:55am",
        "006 - TuThFr 10:10am-12:05pm",
        "007 - TuThFr 12:20pm-2:15pm"
        ]
    elif inpt == "1502spring":
        section.options = [
        "Select your section",
        "001 - MoWeTh 8am-9:55am",
        "002 - MoWeTh 10:10am-12:05pm",
        "003 - MoWeTh 12:20pm-2:15pm",
        "004 - MoWeTh 2:30pm-4:25pm",
        "005 - MoWeTh 4:40pm-6:35pm",
        "006 - TuThFr 8am-9:55am",
        "007 - TuThFr 10:10am-12:05pm",
        "008 - TuThFr 12:20pm-2:15pm"
        ]
    elif inpt == "1401fall":
        section.options = [
        "Select your section",
        "001 - MoTuTh 8am-9:55am",
        "002 - MoTuTh 10:10am-12:05pm",
        "003 - MoTuTh 12:20pm-2:15pm",
        "004 - MoTuTh 2:30pm-4:25pm",
        ]
    elif inpt == "1401spring":
        section.options = [
        "Select your section",
        "001 - MoWeFr 8am-9:55am",
        "002 - MoWeFr 10:10am-12:05pm",
        ]
    elif inpt == "1402fall":
        section.options = [
        "Select your section",
        "001 - MoWeFr 8am-9:55am",
        "002 - MoWeFr 10:10am-12:05pm",
        ]
    elif inpt == "1402spring":
        section.options = [
        "Select your section",
        "001 - MoTuTh 8am-9:55am",
        "002 - MoTuTh 10:10am-12:05pm",
        "003 - MoTuTh 12:20pm-2:15pm",
        "004 - MoTuTh 2:30pm-4:25pm",
        ]
    elif inpt == "1601":
        section.options = ["Select your section","001 - MoWeFr 10:10am-12:05pm",]
    elif inpt == "1602":
        section.options = ["Select your section","001 - MoWeFr 10:10am-12:05pm",]
    else:
        section.options = ["error",]
    
    #displays the course selection dropdown menu.
    display(section)

    #displays the group number textbox.
    display(group)

    #displays the group member names textbox.
    display(names)

    #displays the url textbox.
    display(url)
    
    


#QUESTION ANSWER CELLS
#Protections added in case cell is accidentally re-run - will remember input values as long as kernel is not restarted or closed.
#Input values are NOT remembered if the kernel is restarted!!  They will need to be manually copy-pasted by user from the excel back-up.
#Unfortunately, you need a separate, distinct variable/function for each question/answer.  More info below with legacy code.

answers = [None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None]

def Q(qnumber,labnamexl):
    Question = ipywidgets.Textarea(
        value=answers[qnumber-1],
        placeholder="Type your answer to Q"+str(qnumber)+" here",
        description= "Q"+str(qnumber)+":",
        disabled=False
    )
    answers[qnumber-1] = Question.value
    display(Question)
    workbook = load_workbook(filename=labnamexl+txl+".xlsx")
    sheet = workbook.active
    sheet["A"+str(qnumber)]="Q"+str(qnumber)
    for i in range(len(answers)):
        sheet["B"+str(i+1)]=answers[i]
    workbook.save(filename=labnamexl+txl+".xlsx")




#Question 2 answer cell:
#Q_2 = ipywidgets.Textarea(
#        value=None,
#        placeholder="Type your answer to Q2 here",
#        description= "Q2:",
#        disabled=False
#    )
#def Q2(labnamexl):
#    display(Q_2)
#    answers = [Q_1.value,Q_2.value,Q_3.value,Q_4.value,Q_5.value,Q_6.value,Q_7.value,Q_8.value,Q_9.value,Q_10.value,Q_11.value,Q_12.value,Q_13.value,Q_14.value,Q_15.value,Q_16.value,Q_17.value,Q_18.value]
#    workbook = load_workbook(filename=labnamexl+txl+".xlsx")
#    sheet = workbook.active
#    sheet["A2"]="Q2"
#    for i in range(len(answers)):
#        sheet["B"+str(i+1)]=answers[i]
#    workbook.save(filename=labnamexl+txl+".xlsx")
    
